### ISSUE TITLE
Files are output fps x width instead of width x height

### ISSUE THREAD

**Issue by AzraelNewtype** [arandomliz/mpv-gif-generator#2]
Line 28 currently reads
`    options.fps, options.width, options.height`
and should probably read
`    options.width, options.height`
given that there's only two decimals in the format string and you handled the fps on 25.

I literally cannot be bothered with a PR for this.

**Comment by tyalie** [comment]
Interesting, because it worked for me perfectly. Could it be that some kind of version mismatch is responsible for this?
